apiVersion: v1
kind: Service
metadata:
  name: k8s-jenkins
spec:
  type: LoadBalancer
  selector:
    app: k8s-jenkins
  ports:
  - name: port8080
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-jenkins
  template:
    metadata:
      labels:
        app: k8s-jenkins
    spec:
      containers:
      - name: k8s-jenkins
        image: jenkins/jenkins:lts
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: httpport
          containerPort: 8080
        - name: jnlpport
          containerPort: 50000      

